security:
    password_hashers:
        App\Entity\VermittlerUser: 'auto'
    providers:
        vermittler_user_provider:
            id: App\Security\VermittlerUserProvider
    role_hierarchy:
        ROLE_CORE_ADMIN: VERMITTLER_USER_ROLE
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        foo_jwt:
            pattern: ^/foo/login
            stateless: true
            provider: vermittler_user_provider
            json_login:
                check_path: foo_jwt_login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        foo_jwt_api:
            pattern:   ^/foo
            stateless: true
            jwt:
                provider: vermittler_user_provider
    access_control:
         - { path: ^/foo/docs, roles: PUBLIC_ACCESS }
         - { path: ^/foo/login$, roles: PUBLIC_ACCESS }
         - { path: ^/foo/*$, roles: VERMITTLER_USER_ROLE }
